version: '3'

services:
  redis:
    image: "redis:alpine"

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8080
    volumes:
      - ./parsing_news:/code
    ports:
      - "8080:8080"

  celery:
#    build:
#      dockerfile: Dockerfile
#      context: .
    build: .
    command: celery -A parsing_news worker --loglevel=info
    volumes:
      - ./parsing_news:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A parsing_news beat -S django --loglevel=info
    volumes:
      - ./parsing_news:/code
    depends_on:
      - redis
