---
- hosts: all
  user: vagrant
  sudo: True

  tasks:
    - name: update apt packages
      shell: yum updateinfo
      become: True
      tags: system

    - name: Update yum
      yum: name='*' state=present
      become: True
      tags: system

#    - name: Install yum-utils
#      yum: name=yum-utils
#      become: True
#      tags: system

    - name: Install apt packages
      yum: name='{{ item }}'
      become: True
      with_items:
        - curl
        - gcc.x86_64
        - wget
        - git
        - libxml2-devel.x86_64
        - libxslt-devel.x86_64
        - python-devel.x86_64
        - python35u-devel.x86_64
        - python35u-pip.noarch
        - vim
      tags: system

    - name: Make python default
      raw: alias python=/usr/bin/python3.5
      become: True
      tags: system

    - name: upgrade distribute
      shell: pip3.5 install --upgrade distribute
      tags: system

    - name: Install pip packages
      shell: pip3.5 install -r /home/vagrant/parsing_news_and_send_telegram/requirements.txt
#      environment:
#        PYTHONPATH: '/usr/local/bin/pip'
#        PATH: "/usr/local/bin:{{ (ansible_env|default({})).PATH|default('') }}"
      tags: system
