---
- hosts: all
  user: vagrant
  sudo: True

  vars:
    USER_HOME: "/home/vagrant"
    PROJECT_NAME: "parsing_news_and_send_telegram"
    PROJECT_HOME: "{{ USER_HOME }}/{{ PROJECT_NAME }}"
    SUPERVISOR_FILE: "/etc/supervisor.conf"
    VIRTUALENV_DIR: "{{ USER_HOME }}/virtualenv"
    VIRTUALENV_NAME: "parsing_news_and_send_telegram"
    PARSING_NEWS_VIRTUALENV: "{{ VIRTUALENV_DIR }}/{{ VIRTUALENV_NAME }}"

  tasks:
    - name: yum updateinfo
      shell: yum updateinfo
      become: True
      tags: system

    - name: Update all packages
      yum: name='*' state=latest
      become: True
      tags: system

    - name: Add nginx repo
      shell: rm -f /etc/yum.repos.d/nginx.repo && ln -s {{ PROJECT_HOME }}/etc/nginx/nginx.repo /etc/yum.repos.d/nginx.repo
      become: True
      tags: system

    - name: Install apt packages
      yum: name='{{ item }}'
      become: True
      with_items:
        - yum-utils
        - curl
        - gcc.x86_64
        - wget
        - git
        - libxml2-devel.x86_64
        - libxslt-devel.x86_64
        - vim
        - epel-release
        - nginx
        - yum-utils
        - php-curl
      ignore_errors: True
      tags: system

    - name: mkdir for nginx
      shell: mkdir -p /var/log/nginx/ && mkdir -p /etc/nginx/nginx.conf
      become: True
      tags: system

    - name: Add nginx repo
      shell: rm -f {{ SUPERVISOR_FILE }} && cp {{ PROJECT_HOME }}/etc/nginx/vagraant.nginx.conf /etc/nginx/nginx.conf
      become: True
      tags: system

#    - name: Restart nginx
#      shell: nginx reload
#      become: True
#      tags:
#        - system
#        - nginx

    - name: install the CentOS Development Tools
      # which are used to allow you to build and compile software
      command: yum -y groupinstall development
      become: True
      tags: system

    - name: Install python3.6
      command: "yum -y install {{ item }}"
      with_items:
        - https://centos7.iuscommunity.org/ius-release.rpm
        - python36u
        - python36u-pip
        - python36u-devel
      sudo: True
      tags: system

    - name: Install virtualenv
      command: "{{ item }}"
      with_items:
        - pip3.5 install virtualenv
        - mkdir -p {{ VIRTUALENV_DIR }}
      tags: system

    - name: Initiate virtualenv
      pip: virtualenv="{{ PARSING_NEWS_VIRTUALENV }}"
           virtualenv_python=python3.6
           requirements={{ PROJECT_HOME }}/requirements.txt
      tags:
        - system
        - backend
        - restart

    - name: migrate DB
      pip: virtualenv="{{ PARSING_NEWS_VIRTUALENV }}"
           virtualenv_python=python3.6
           requirements={{ PROJECT_HOME }}/requirements.txt
      tags:
        - system
        - backend
        - database

    - name: install supervisor
      command: "{{ item }}"
      with_items:
        - yum install -y python-setuptools
        - easy_install supervisor
        - mkdir /tmp/logs/
      become: True
      tags:
        - system
        - backend

    - name: add supervisor scripts
      command: "{{ item }}"
      with_items:
        - echo_supervisord_conf > {{ SUPERVISOR_FILE }}
        - cp {{ PROJECT_HOME }}/etc/supervisor/* >> {{ SUPERVISOR_FILE }}
        - sudo supervisord -c {{ SUPERVISOR_FILE }}
        - sudo supervisorctl -c {{ SUPERVISOR_FILE }}
      become: True
      tags:
        - system
        - restart
        - backend

    - name: restart supervisor
      command: "supervisorctl {{ item }}"
      with_items:
        - reread
        - update
        - restart all
      sudo: True
      tags:
        - system
        - restart
        - backend
